### ISSUE TITLE
`Cannot find ('compose/GITSHA', 'compose/GITSHA', 1, 'x')`

### ISSUE THREAD

**Issue by vertexvaar** [ubiquiti/docker-compose-aarch64#12]
In Step 15 i get following output after the process ran for > 20 Minutes:
```
Step 13/15 : RUN mkdir ./dist     && pip install -q -r requirements.txt -r requirements-build.txt     && ./script/build/write-git-sha     && pyinstaller docker-compose.spec     && mv dist/docker-compose ./docker-compose-$(uname -s)-$(uname -m)
 ---> Running in de31b22ea62d

8d51620a
366 INFO: PyInstaller: 3.6
368 INFO: Python: 3.6.5
375 INFO: Platform: Linux-5.3.0-40-generic-aarch64-with-debian-9.4
380 INFO: UPX is not available.
387 INFO: Extending PYTHONPATH with paths
['/build/dockercompose/bin', '/build/dockercompose']
387 INFO: checking Analysis
388 INFO: Building Analysis because Analysis-00.toc is non existent
388 INFO: Initializing module dependency graph...
395 INFO: Caching module graph hooks...
452 INFO: Analyzing base_library.zip ...
34339 INFO: Caching module dependency graph...
35212 INFO: running Analysis Analysis-00.toc
35422 INFO: Analyzing bin/docker-compose
36456 INFO: Processing pre-find module path hook   distutils
36458 INFO: distutils: retargeting to non-venv dir '/usr/local/lib/python3.6'
38141 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
50585 INFO: Processing pre-safe import module hook   six.moves
90159 INFO: Processing module hooks...
90161 INFO: Loading module hook "hook-certifi.py"...
90165 INFO: Loading module hook "hook-cryptography.py"...
91567 INFO: Loading module hook "hook-jsonschema.py"...
91580 INFO: Loading module hook "hook-importlib_metadata.py"...
91587 INFO: Loading module hook "hook-distutils.py"...
91593 INFO: Loading module hook "hook-encodings.py"...
92097 INFO: Loading module hook "hook-nacl.py"...
92104 INFO: Loading module hook "hook-pydoc.py"...
92106 INFO: Loading module hook "hook-xml.py"...
92927 INFO: Looking for ctypes DLLs
93434 INFO: Analyzing run-time hooks ...
93501 INFO: Including run-time hook 'pyi_rth_certifi.py'
93508 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
93657 INFO: Looking for dynamic libraries
100774 INFO: Looking for eggs
100774 INFO: Using Python library /usr/local/lib/libpython3.6m.so.1.0
100848 INFO: Warnings written to /build/dockercompose/build/docker-compose/warn-docker-compose.txt
101618 INFO: Graph cross-reference written to /build/dockercompose/build/docker-compose/xref-docker-compose.html
101857 INFO: checking PYZ
101857 INFO: Building PYZ because PYZ-00.toc is non existent
101857 INFO: Building PYZ (ZlibArchive) /build/dockercompose/build/docker-compose/PYZ-00.pyz
108207 INFO: Building PYZ (ZlibArchive) /build/dockercompose/build/docker-compose/PYZ-00.pyz completed successfully.
108373 INFO: checking PKG
108373 INFO: Building PKG because PKG-00.toc is non existent
108373 INFO: Building PKG (CArchive) PKG-00.pkg
Cannot find ('compose/GITSHA', 'compose/GITSHA', 1, 'x')
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 734, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 681, in build
    exec(code, spec_namespace)
  File "docker-compose.spec", line 102, in <module>
    bootloader_ignore_signals=True)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/api.py", line 436, in __init__
    upx_exclude=self.upx_exclude
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/api.py", line 199, in __init__
    self.__postinit__()
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/datastruct.py", line 160, in __postinit__
    self.assemble()
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/api.py", line 284, in assemble
    pylib_name=pylib_name)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/archive/writers.py", line 336, in __init__
    super(CArchiveWriter, self).__init__(archive_path, logical_toc)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/archive/writers.py", line 63, in __init__
    self._add_from_table_of_contents(logical_toc)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/archive/writers.py", line 88, in _add_from_table_of_contents
    self.add(toc_entry)  # The guts of the archive.
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/archive/writers.py", line 383, in add
    fh = open(pathnm, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'compose/GITSHA'
The command '/bin/sh -c mkdir ./dist     && pip install -q -r requirements.txt -r requirements-build.txt     && ./script/build/write-git-sha     && pyinstaller docker-compose.spec     && mv dist/docker-compose ./docker-compose-$(uname -s)-$(uname -m)' returned a non-zero code: 1
```

**Comment by vertexvaar** [comment]
I edited the Dockerfile before.
I've set `ENV DOCKER_COMPOSE_VER 1.25.4` and added a pip upgrade before six install `RUN pip install --upgrade pip && pip install six==$SIX_VER`
